--------------------------------------------------------
--  파일이 생성됨 - 화요일-2월-23-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ADDRESSBOOK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BITWORK"."ADDRESSBOOK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 156 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BOARD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BITWORK"."BOARD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 15 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COMMENTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BITWORK"."COMMENTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COMPANY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BITWORK"."COMPANY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 16 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SIGN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BITWORK"."SIGN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 40 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ADDRESSBOOK
--------------------------------------------------------

  CREATE TABLE "BITWORK"."ADDRESSBOOK" 
   (	"ADDRESSBOOK_IDX" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"PHONE" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"COMPANY" VARCHAR2(50 BYTE), 
	"COMPANY_IDX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BITWORK"."ADDRESSBOOK"."ADDRESSBOOK_IDX" IS '주소록 번호';
   COMMENT ON COLUMN "BITWORK"."ADDRESSBOOK"."NAME" IS '이름';
   COMMENT ON COLUMN "BITWORK"."ADDRESSBOOK"."PHONE" IS '전화번호';
   COMMENT ON COLUMN "BITWORK"."ADDRESSBOOK"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "BITWORK"."ADDRESSBOOK"."COMPANY" IS '회사명';
   COMMENT ON COLUMN "BITWORK"."ADDRESSBOOK"."COMPANY_IDX" IS '유저의 회사번호';
   COMMENT ON TABLE "BITWORK"."ADDRESSBOOK"  IS '주소록';
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "BITWORK"."BOARD" 
   (	"BOARD_IDX" NUMBER, 
	"MEMBER_ID" VARCHAR2(30 BYTE), 
	"STATUS" NUMBER(1,0) DEFAULT 1, 
	"SUBJECT" VARCHAR2(100 BYTE),
	"CONTENT" VARCHAR2(3000 BYTE),
	"FILE_NAME" VARCHAR2(50 BYTE), 
	"ORI_NAME" VARCHAR2(50 BYTE), 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"HIT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BITWORK"."BOARD"."BOARD_IDX" IS '글번호';
   COMMENT ON COLUMN "BITWORK"."BOARD"."MEMBER_ID" IS '회원 아이디';
   COMMENT ON COLUMN "BITWORK"."BOARD"."STATUS" IS '0(공지글), 1(일반글)';
   COMMENT ON COLUMN "BITWORK"."BOARD"."SUBJECT" IS '제목';
   COMMENT ON COLUMN "BITWORK"."BOARD"."CONTENT" IS '내용';
   COMMENT ON COLUMN "BITWORK"."BOARD"."FILE_NAME" IS '파일시스템에 저장된 실제 이름';
   COMMENT ON COLUMN "BITWORK"."BOARD"."ORI_NAME" IS '사용자가 올린 파일 이름';
   COMMENT ON COLUMN "BITWORK"."BOARD"."REGDATE" IS '글 등록일';
--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "BITWORK"."COMMENTS" 
   (	"CMT_IDX" NUMBER, 
	"MEMBER_ID" VARCHAR2(30 BYTE), 
	"CMT_CONTENT" VARCHAR2(300 BYTE), 
	"CMT_DATE" DATE DEFAULT SYSDATE, 
	"BOARD_IDX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMMUTE
--------------------------------------------------------

  CREATE TABLE "BITWORK"."COMMUTE" 
   (	"MEMBER_ID" VARCHAR2(30 BYTE), 
	"C_DATE" DATE DEFAULT TRUNC(SYSDATE), 
	"ON_TIME" DATE DEFAULT SYSDATE, 
	"OFF_TIME" DATE, 
	"STATUS" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BITWORK"."COMMUTE"."MEMBER_ID" IS '회원 아이디';
   COMMENT ON COLUMN "BITWORK"."COMMUTE"."C_DATE" IS '출근일자';
   COMMENT ON COLUMN "BITWORK"."COMMUTE"."ON_TIME" IS '출근시간';
   COMMENT ON COLUMN "BITWORK"."COMMUTE"."OFF_TIME" IS '퇴근시간';
   COMMENT ON COLUMN "BITWORK"."COMMUTE"."STATUS" IS '출근시간이 9시보다 크면 1(지각), 0(정상)';
   COMMENT ON TABLE "BITWORK"."COMMUTE"  IS '출퇴근 기록';
--------------------------------------------------------
--  DDL for Table COMPANY
--------------------------------------------------------

  CREATE TABLE "BITWORK"."COMPANY" 
   (	"COMPANY_IDX" NUMBER, 
	"COMPANY_NAME" VARCHAR2(50 BYTE), 
	"COMPANY_PHONE" VARCHAR2(30 BYTE), 
	"COMPANY_EMAIL" VARCHAR2(50 BYTE), 
	"COMPANY_EMP_CNT" NUMBER DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BITWORK"."COMPANY"."COMPANY_IDX" IS '회사번호';
   COMMENT ON COLUMN "BITWORK"."COMPANY"."COMPANY_NAME" IS '회사명';
   COMMENT ON COLUMN "BITWORK"."COMPANY"."COMPANY_PHONE" IS '회사전화번호';
   COMMENT ON COLUMN "BITWORK"."COMPANY"."COMPANY_EMAIL" IS '회사이메일(유니크)';
   COMMENT ON COLUMN "BITWORK"."COMPANY"."COMPANY_EMP_CNT" IS '사원수';
   COMMENT ON TABLE "BITWORK"."COMPANY"  IS '회사';
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "BITWORK"."MEMBER" 
   (	"ID" VARCHAR2(30 BYTE), 
	"PW" VARCHAR2(30 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"PHONE" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"POSITION" VARCHAR2(50 BYTE) DEFAULT '사원', 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"COMPANY_IDX" NUMBER, 
	"JOINDATE" DATE, 
	"GRADE" NUMBER, 
	"FILE_NAME" VARCHAR2(300 BYTE), 
	"ORI_NAME" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BITWORK"."MEMBER"."ID" IS '아이디';
   COMMENT ON COLUMN "BITWORK"."MEMBER"."PW" IS '비밀번호';
   COMMENT ON COLUMN "BITWORK"."MEMBER"."NAME" IS '이름';
   COMMENT ON COLUMN "BITWORK"."MEMBER"."PHONE" IS '전화번호';
   COMMENT ON COLUMN "BITWORK"."MEMBER"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "BITWORK"."MEMBER"."POSITION" IS '직급';
   COMMENT ON COLUMN "BITWORK"."MEMBER"."REGDATE" IS '가입일자';
   COMMENT ON COLUMN "BITWORK"."MEMBER"."COMPANY_IDX" IS '회사번호';
   COMMENT ON COLUMN "BITWORK"."MEMBER"."JOINDATE" IS '입사일자';
   COMMENT ON COLUMN "BITWORK"."MEMBER"."GRADE" IS '등급(0:소속없음, 1:초대, 2:신청, 3:직원, 4:사장)';
   COMMENT ON TABLE "BITWORK"."MEMBER"  IS '회원';
--------------------------------------------------------
--  DDL for Table SIGN
--------------------------------------------------------

  CREATE TABLE "BITWORK"."SIGN" 
   (	"DOC_NO" NUMBER, 
	"DOC_TITLE" VARCHAR2(50 BYTE), 
	"MEMBER_ID" VARCHAR2(30 BYTE), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"SIGN_DATE" DATE, 
	"DOC_STATUS" VARCHAR2(10 BYTE) DEFAULT '대기', 
	"DOC_CONTENT" VARCHAR2(1500 BYTE), 
	"FILE_NAME" VARCHAR2(50 BYTE), 
	"ORI_NAME" VARCHAR2(50 BYTE), 
	"USER_READ" NUMBER(1,0) DEFAULT 0, 
	"BOSS_READ" NUMBER(1,0) DEFAULT 0, 
	"WRITER_NAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BITWORK"."SIGN"."DOC_NO" IS '문서번호';
   COMMENT ON COLUMN "BITWORK"."SIGN"."DOC_TITLE" IS '제목';
   COMMENT ON COLUMN "BITWORK"."SIGN"."MEMBER_ID" IS '회원아이디';
   COMMENT ON COLUMN "BITWORK"."SIGN"."INSERT_DATE" IS '작성일자';
   COMMENT ON COLUMN "BITWORK"."SIGN"."SIGN_DATE" IS '결재일';
   COMMENT ON COLUMN "BITWORK"."SIGN"."DOC_STATUS" IS '결재상태';
   COMMENT ON COLUMN "BITWORK"."SIGN"."DOC_CONTENT" IS '결재 문서 내용';
   COMMENT ON COLUMN "BITWORK"."SIGN"."FILE_NAME" IS '파일시스템에 저장된 실제 이름';
   COMMENT ON COLUMN "BITWORK"."SIGN"."ORI_NAME" IS '사용자가 올린 파일 이름';
   COMMENT ON COLUMN "BITWORK"."SIGN"."USER_READ" IS '읽으면 1';
   COMMENT ON COLUMN "BITWORK"."SIGN"."BOSS_READ" IS '읽으면 1';
   COMMENT ON TABLE "BITWORK"."SIGN"  IS '전자결재';
--------------------------------------------------------
--  DDL for Table COMPANY
--------------------------------------------------------

  CREATE TABLE "BITWORK"."COMPANY" 
   (	"COMPANY_IDX" NUMBER, 
	"COMPANY_NAME" VARCHAR2(50 BYTE), 
	"COMPANY_PHONE" VARCHAR2(30 BYTE), 
	"COMPANY_EMAIL" VARCHAR2(50 BYTE), 
	"COMPANY_EMP_CNT" NUMBER DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BITWORK"."COMPANY"."COMPANY_IDX" IS '회사번호';
   COMMENT ON COLUMN "BITWORK"."COMPANY"."COMPANY_NAME" IS '회사명';
   COMMENT ON COLUMN "BITWORK"."COMPANY"."COMPANY_PHONE" IS '회사전화번호';
   COMMENT ON COLUMN "BITWORK"."COMPANY"."COMPANY_EMAIL" IS '회사이메일(유니크)';
   COMMENT ON COLUMN "BITWORK"."COMPANY"."COMPANY_EMP_CNT" IS '사원수';
   COMMENT ON TABLE "BITWORK"."COMPANY"  IS '회사';
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "BITWORK"."MEMBER" 
   (	"ID" VARCHAR2(30 BYTE), 
	"PW" VARCHAR2(30 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"PHONE" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"POSITION" VARCHAR2(50 BYTE) DEFAULT '사원', 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"COMPANY_IDX" NUMBER, 
	"JOINDATE" DATE, 
	"GRADE" NUMBER, 
	"FILE_NAME" VARCHAR2(300 BYTE), 
	"ORI_NAME" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BITWORK"."MEMBER"."ID" IS '아이디';
   COMMENT ON COLUMN "BITWORK"."MEMBER"."PW" IS '비밀번호';
   COMMENT ON COLUMN "BITWORK"."MEMBER"."NAME" IS '이름';
   COMMENT ON COLUMN "BITWORK"."MEMBER"."PHONE" IS '전화번호';
   COMMENT ON COLUMN "BITWORK"."MEMBER"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "BITWORK"."MEMBER"."POSITION" IS '직급';
   COMMENT ON COLUMN "BITWORK"."MEMBER"."REGDATE" IS '가입일자';
   COMMENT ON COLUMN "BITWORK"."MEMBER"."COMPANY_IDX" IS '회사번호';
   COMMENT ON COLUMN "BITWORK"."MEMBER"."JOINDATE" IS '입사일자';
   COMMENT ON COLUMN "BITWORK"."MEMBER"."GRADE" IS '등급(0:소속없음, 1:초대, 2:신청, 3:직원, 4:사장)';
   COMMENT ON TABLE "BITWORK"."MEMBER"  IS '회원';
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "BITWORK"."BOARD" 
   (	"BOARD_IDX" NUMBER, 
	"MEMBER_ID" VARCHAR2(30 BYTE), 
	"STATUS" NUMBER(1,0) DEFAULT 1, 
	"SUBJECT" VARCHAR2(30 BYTE), 
	"CONTENT" VARCHAR2(1500 BYTE), 
	"FILE_NAME" VARCHAR2(50 BYTE), 
	"ORI_NAME" VARCHAR2(50 BYTE), 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"HIT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BITWORK"."BOARD"."BOARD_IDX" IS '글번호';
   COMMENT ON COLUMN "BITWORK"."BOARD"."MEMBER_ID" IS '회원 아이디';
   COMMENT ON COLUMN "BITWORK"."BOARD"."STATUS" IS '0(공지글), 1(일반글)';
   COMMENT ON COLUMN "BITWORK"."BOARD"."SUBJECT" IS '제목';
   COMMENT ON COLUMN "BITWORK"."BOARD"."CONTENT" IS '내용';
   COMMENT ON COLUMN "BITWORK"."BOARD"."FILE_NAME" IS '파일시스템에 저장된 실제 이름';
   COMMENT ON COLUMN "BITWORK"."BOARD"."ORI_NAME" IS '사용자가 올린 파일 이름';
   COMMENT ON COLUMN "BITWORK"."BOARD"."REGDATE" IS '글 등록일';
--------------------------------------------------------
--  DDL for Table ADDRESSBOOK
--------------------------------------------------------

  CREATE TABLE "BITWORK"."ADDRESSBOOK" 
   (	"ADDRESSBOOK_IDX" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"PHONE" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"COMPANY" VARCHAR2(50 BYTE), 
	"COMPANY_IDX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BITWORK"."ADDRESSBOOK"."ADDRESSBOOK_IDX" IS '주소록 번호';
   COMMENT ON COLUMN "BITWORK"."ADDRESSBOOK"."NAME" IS '이름';
   COMMENT ON COLUMN "BITWORK"."ADDRESSBOOK"."PHONE" IS '전화번호';
   COMMENT ON COLUMN "BITWORK"."ADDRESSBOOK"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "BITWORK"."ADDRESSBOOK"."COMPANY" IS '회사명';
   COMMENT ON COLUMN "BITWORK"."ADDRESSBOOK"."COMPANY_IDX" IS '유저의 회사번호';
   COMMENT ON TABLE "BITWORK"."ADDRESSBOOK"  IS '주소록';
--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "BITWORK"."COMMENTS" 
   (	"CMT_IDX" NUMBER, 
	"MEMBER_ID" VARCHAR2(30 BYTE), 
	"CMT_CONTENT" VARCHAR2(300 BYTE), 
	"CMT_DATE" DATE DEFAULT SYSDATE, 
	"BOARD_IDX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMMUTE
--------------------------------------------------------

  CREATE TABLE "BITWORK"."COMMUTE" 
   (	"MEMBER_ID" VARCHAR2(30 BYTE), 
	"C_DATE" DATE DEFAULT TRUNC(SYSDATE), 
	"ON_TIME" DATE DEFAULT SYSDATE, 
	"OFF_TIME" DATE, 
	"STATUS" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BITWORK"."COMMUTE"."MEMBER_ID" IS '회원 아이디';
   COMMENT ON COLUMN "BITWORK"."COMMUTE"."C_DATE" IS '출근일자';
   COMMENT ON COLUMN "BITWORK"."COMMUTE"."ON_TIME" IS '출근시간';
   COMMENT ON COLUMN "BITWORK"."COMMUTE"."OFF_TIME" IS '퇴근시간';
   COMMENT ON COLUMN "BITWORK"."COMMUTE"."STATUS" IS '출근시간이 9시보다 크면 1(지각), 0(정상)';
   COMMENT ON TABLE "BITWORK"."COMMUTE"  IS '출퇴근 기록';
--------------------------------------------------------
--  DDL for Table SIGN
--------------------------------------------------------

  CREATE TABLE "BITWORK"."SIGN" 
   (	"DOC_NO" NUMBER, 
	"DOC_TITLE" VARCHAR2(50 BYTE), 
	"MEMBER_ID" VARCHAR2(30 BYTE), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"SIGN_DATE" DATE, 
	"DOC_STATUS" VARCHAR2(10 BYTE) DEFAULT '대기', 
	"DOC_CONTENT" VARCHAR2(1500 BYTE), 
	"FILE_NAME" VARCHAR2(50 BYTE), 
	"ORI_NAME" VARCHAR2(50 BYTE), 
	"USER_READ" NUMBER(1,0) DEFAULT 0, 
	"BOSS_READ" NUMBER(1,0) DEFAULT 0, 
	"WRITER_NAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BITWORK"."SIGN"."DOC_NO" IS '문서번호';
   COMMENT ON COLUMN "BITWORK"."SIGN"."DOC_TITLE" IS '제목';
   COMMENT ON COLUMN "BITWORK"."SIGN"."MEMBER_ID" IS '회원아이디';
   COMMENT ON COLUMN "BITWORK"."SIGN"."INSERT_DATE" IS '작성일자';
   COMMENT ON COLUMN "BITWORK"."SIGN"."SIGN_DATE" IS '결재일';
   COMMENT ON COLUMN "BITWORK"."SIGN"."DOC_STATUS" IS '결재상태';
   COMMENT ON COLUMN "BITWORK"."SIGN"."DOC_CONTENT" IS '결재 문서 내용';
   COMMENT ON COLUMN "BITWORK"."SIGN"."FILE_NAME" IS '파일시스템에 저장된 실제 이름';
   COMMENT ON COLUMN "BITWORK"."SIGN"."ORI_NAME" IS '사용자가 올린 파일 이름';
   COMMENT ON COLUMN "BITWORK"."SIGN"."USER_READ" IS '읽으면 1';
   COMMENT ON COLUMN "BITWORK"."SIGN"."BOSS_READ" IS '읽으면 1';
   COMMENT ON TABLE "BITWORK"."SIGN"  IS '전자결재';
REM INSERTING into BITWORK.ADDRESSBOOK
SET DEFINE OFF;
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (155,'미노2','010-5299-6429','minho1030@naver.com','비트캠프',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (47,'test1','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (48,'test2','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (49,'test3','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (50,'test4','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (51,'test5','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (52,'test6','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (53,'test7','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (54,'test8','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (55,'test9','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (56,'test10','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (57,'test11','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (58,'test12','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (59,'test1','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (60,'test2','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (61,'test3','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (62,'test4','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (63,'test5','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (64,'test6','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (65,'test7','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (66,'test8','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (67,'test9','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (68,'test10','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (69,'test11','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (70,'test12','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (71,'test1','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (72,'test2','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (73,'test3','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (74,'test4','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (75,'test5','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (76,'test6','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (77,'test7','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (78,'test8','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (79,'test9','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (80,'test10','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (81,'test11','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (82,'test12','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (83,'test1','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (84,'test2','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (85,'test3','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (86,'test4','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (87,'test5','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (88,'test6','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (89,'test7','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (90,'test8','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (91,'test9','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (92,'test10','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (93,'test11','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (94,'test12','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (95,'test1','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (96,'test2','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (97,'test3','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (98,'test4','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (99,'test5','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (100,'test6','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (101,'test7','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (102,'test8','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (103,'test9','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (104,'test10','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (105,'test11','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (106,'test12','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (107,'test1','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (108,'test2','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (109,'test3','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (110,'test4','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (111,'test5','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (112,'test6','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (113,'test7','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (114,'test8','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (115,'test9','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (116,'test10','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (117,'test11','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (118,'test12','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (119,'test1','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (120,'test2','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (121,'test3','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (122,'test4','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (123,'test5','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (124,'test6','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (125,'test7','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (126,'test8','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (127,'test9','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (128,'test10','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (129,'test11','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (130,'test12','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (131,'test1','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (132,'test2','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (133,'test3','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (134,'test4','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (135,'test5','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (136,'test6','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (137,'test7','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (138,'test8','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (139,'test9','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (140,'test10','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (141,'test11','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (142,'test12','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (145,'test3','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (146,'test4','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (147,'test5','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (148,'test6','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (149,'test7','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (150,'test8','010-1234-5678','test@test.com','test',15);
Insert into BITWORK.ADDRESSBOOK (ADDRESSBOOK_IDX,NAME,PHONE,EMAIL,COMPANY,COMPANY_IDX) values (151,'test9','010-1234-5678','test@test.com','test',15);
REM INSERTING into BITWORK.BOARD
SET DEFINE OFF;
REM INSERTING into BITWORK.COMMENTS
SET DEFINE OFF;
REM INSERTING into BITWORK.COMMUTE
SET DEFINE OFF;
REM INSERTING into BITWORK.COMPANY
SET DEFINE OFF;
Insert into BITWORK.COMPANY (COMPANY_IDX,COMPANY_NAME,COMPANY_PHONE,COMPANY_EMAIL,COMPANY_EMP_CNT) values (15,'mino','010-5299-6429','minho1030@naver.com',5);
REM INSERTING into BITWORK.MEMBER
SET DEFINE OFF;
Insert into BITWORK.MEMBER (ID,PW,NAME,PHONE,EMAIL,POSITION,REGDATE,COMPANY_IDX,JOINDATE,GRADE,FILE_NAME,ORI_NAME) values ('cothis','1111','미노','010-5299-6429','minho1030@naver.com','사원',to_date('21/02/15','RR/MM/DD'),15,to_date('21/02/18','RR/MM/DD'),4,'main.png','main.png');
Insert into BITWORK.MEMBER (ID,PW,NAME,PHONE,EMAIL,POSITION,REGDATE,COMPANY_IDX,JOINDATE,GRADE,FILE_NAME,ORI_NAME) values ('test','1111','test','010-5299-6429','test@test.com','사원',to_date('21/02/20','RR/MM/DD'),15,to_date('21/02/20','RR/MM/DD'),3,'main3.png','main.png');
Insert into BITWORK.MEMBER (ID,PW,NAME,PHONE,EMAIL,POSITION,REGDATE,COMPANY_IDX,JOINDATE,GRADE,FILE_NAME,ORI_NAME) values ('yuna1880','1111','유나','010-5299-6429','aaa@naver.com','사원',to_date('21/02/15','RR/MM/DD'),15,to_date('21/02/18','RR/MM/DD'),3,'profile1.jpg','profile1.jpg');
Insert into BITWORK.MEMBER (ID,PW,NAME,PHONE,EMAIL,POSITION,REGDATE,COMPANY_IDX,JOINDATE,GRADE,FILE_NAME,ORI_NAME) values ('hana','1111','hana','010-3333-5555','hana@naver.com','사원',to_date('21/02/17','RR/MM/DD'),15,to_date('21/02/18','RR/MM/DD'),3,'main2.png','main.png');
Insert into BITWORK.MEMBER (ID,PW,NAME,PHONE,EMAIL,POSITION,REGDATE,COMPANY_IDX,JOINDATE,GRADE,FILE_NAME,ORI_NAME) values ('admin','admin','admin','010-0000-0000','admin@bitworks.com','사원',to_date('21/02/09','RR/MM/DD'),15,null,1,null,null);
Insert into BITWORK.MEMBER (ID,PW,NAME,PHONE,EMAIL,POSITION,REGDATE,COMPANY_IDX,JOINDATE,GRADE,FILE_NAME,ORI_NAME) values ('jinyoung','1111','진영','010-1234-5678','jinyoung@naver.com','대리',to_date('21/02/16','RR/MM/DD'),15,to_date('21/02/18','RR/MM/DD'),3,'main1.png','main.png');
REM INSERTING into BITWORK.SIGN
SET DEFINE OFF;
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (37,'1월 28일 공부인증합니다','hana',to_date('21/02/20','RR/MM/DD'),null,'완료','뮤',null,null,0,0,'hana');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (38,'안마해주까?','hana',to_date('21/02/20','RR/MM/DD'),to_date('21/02/20','RR/MM/DD'),'완료','네',null,null,1,1,'hana');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (39,'4일차 공부인증','hana',to_date('21/02/20','RR/MM/DD'),to_date('21/02/20','RR/MM/DD'),'완료','ㄴㅇㅀㄴㅀ',null,null,1,1,'hana');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (29,'1월 28일 공부인증합니다','cothis',to_date('21/02/19','RR/MM/DD'),to_date('21/02/20','RR/MM/DD'),'반려','1234',null,null,0,0,'민호');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (30,'asdgsadg','cothis',to_date('21/02/19','RR/MM/DD'),to_date('21/02/20','RR/MM/DD'),'반려','zzdfad',null,null,0,0,'민호');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (31,'1월 28일 공부인증합니다','cothis',to_date('21/02/19','RR/MM/DD'),to_date('21/02/20','RR/MM/DD'),'반려','1234',null,null,0,0,'민호');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (32,'1월 28일 공부인증합니다','cothis',to_date('21/02/19','RR/MM/DD'),to_date('21/02/20','RR/MM/DD'),'반려','1234',null,null,0,0,'민호');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (33,'1월 28일 공부인증합니다','cothis',to_date('21/02/19','RR/MM/DD'),to_date('21/02/20','RR/MM/DD'),'반려','1234',null,null,0,0,'민호');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (34,'1월 28일 공부인증합니다','cothis',to_date('21/02/19','RR/MM/DD'),to_date('21/02/20','RR/MM/DD'),'완료','1234',null,null,0,0,'민호');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (35,'1월 28일 공부인증합니다','cothis',to_date('21/02/19','RR/MM/DD'),null,'완료','1234',null,null,0,0,'민호');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (36,'결재해주세요','hana',to_date('21/02/20','RR/MM/DD'),null,'완료','!!!!',null,null,0,1,'hana');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (1,'test1','cothis',to_date('21/02/19','RR/MM/DD'),null,'대기','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (2,'test2','cothis',to_date('21/02/19','RR/MM/DD'),null,'대기','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (3,'test3','cothis',to_date('21/02/19','RR/MM/DD'),null,'대기','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (4,'test4','cothis',to_date('21/02/19','RR/MM/DD'),null,'완료','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (5,'test5','cothis',to_date('21/02/19','RR/MM/DD'),null,'대기','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (6,'test6','cothis',to_date('21/02/19','RR/MM/DD'),null,'대기','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (7,'test7','cothis',to_date('21/02/19','RR/MM/DD'),null,'완료','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (8,'test8','cothis',to_date('21/02/19','RR/MM/DD'),null,'대기','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (9,'test9','cothis',to_date('21/02/19','RR/MM/DD'),null,'대기','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (10,'test10','cothis',to_date('21/02/19','RR/MM/DD'),null,'대기','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (11,'test11','cothis',to_date('21/02/19','RR/MM/DD'),null,'대기','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (12,'test12','cothis',to_date('21/02/19','RR/MM/DD'),null,'반려','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (13,'test13','cothis',to_date('21/02/19','RR/MM/DD'),null,'반려','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (14,'test14','cothis',to_date('21/02/19','RR/MM/DD'),null,'대기','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (15,'test15','cothis',to_date('21/02/19','RR/MM/DD'),null,'대기','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (16,'test16','cothis',to_date('21/02/19','RR/MM/DD'),null,'대기','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (17,'test17','cothis',to_date('21/02/19','RR/MM/DD'),null,'대기','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (18,'test18','cothis',to_date('21/02/19','RR/MM/DD'),null,'대기','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (19,'test19','cothis',to_date('21/02/19','RR/MM/DD'),null,'대기','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (20,'test20','cothis',to_date('21/02/19','RR/MM/DD'),null,'대기','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (21,'test21','cothis',to_date('21/02/19','RR/MM/DD'),null,'대기','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (22,'test22','cothis',to_date('21/02/19','RR/MM/DD'),null,'대기','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (23,'test23','cothis',to_date('21/02/19','RR/MM/DD'),null,'대기','test내용',null,null,0,0,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (24,'test24','cothis',to_date('21/02/19','RR/MM/DD'),null,'대기','test내용',null,null,0,1,'cothis');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (26,'1월 28일 공부인증합니다','cothis',to_date('21/02/19','RR/MM/DD'),to_date('21/02/20','RR/MM/DD'),'반려','1234',null,null,0,0,'민호');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (27,'zxcb','cothis',to_date('21/02/19','RR/MM/DD'),to_date('21/02/20','RR/MM/DD'),'반려','asdf','ovenapp.txt','ovenapp.txt',0,0,'민호');
Insert into BITWORK.SIGN (DOC_NO,DOC_TITLE,MEMBER_ID,INSERT_DATE,SIGN_DATE,DOC_STATUS,DOC_CONTENT,FILE_NAME,ORI_NAME,USER_READ,BOSS_READ,WRITER_NAME) values (28,'asdgsadg','cothis',to_date('21/02/19','RR/MM/DD'),to_date('21/02/20','RR/MM/DD'),'반려','zzdfad','ovenapp1.txt','ovenapp.txt',0,0,'민호');
--------------------------------------------------------
--  DDL for Index ADDRESSBOOK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITWORK"."ADDRESSBOOK_PK" ON "BITWORK"."ADDRESSBOOK" ("ADDRESSBOOK_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITWORK"."BOARD_PK" ON "BITWORK"."BOARD" ("BOARD_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITWORK"."COMMENTS_PK" ON "BITWORK"."COMMENTS" ("CMT_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMMUTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITWORK"."COMMUTE_PK" ON "BITWORK"."COMMUTE" ("MEMBER_ID", "C_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMPANY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITWORK"."COMPANY_PK" ON "BITWORK"."COMPANY" ("COMPANY_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITWORK"."MEMBER_PK" ON "BITWORK"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIGN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITWORK"."SIGN_PK" ON "BITWORK"."SIGN" ("DOC_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UC_COMPANY_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITWORK"."UC_COMPANY_EMAIL" ON "BITWORK"."COMPANY" ("COMPANY_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UC_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITWORK"."UC_EMAIL" ON "BITWORK"."MEMBER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADDRESSBOOK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITWORK"."ADDRESSBOOK_PK" ON "BITWORK"."ADDRESSBOOK" ("ADDRESSBOOK_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITWORK"."BOARD_PK" ON "BITWORK"."BOARD" ("BOARD_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITWORK"."COMMENTS_PK" ON "BITWORK"."COMMENTS" ("CMT_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMMUTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITWORK"."COMMUTE_PK" ON "BITWORK"."COMMUTE" ("MEMBER_ID", "C_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMPANY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITWORK"."COMPANY_PK" ON "BITWORK"."COMPANY" ("COMPANY_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UC_COMPANY_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITWORK"."UC_COMPANY_EMAIL" ON "BITWORK"."COMPANY" ("COMPANY_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITWORK"."MEMBER_PK" ON "BITWORK"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UC_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITWORK"."UC_EMAIL" ON "BITWORK"."MEMBER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIGN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITWORK"."SIGN_PK" ON "BITWORK"."SIGN" ("DOC_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADDRESSBOOK
--------------------------------------------------------

  ALTER TABLE "BITWORK"."ADDRESSBOOK" ADD CONSTRAINT "ADDRESSBOOK_PK" PRIMARY KEY ("ADDRESSBOOK_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BITWORK"."ADDRESSBOOK" MODIFY ("COMPANY" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."ADDRESSBOOK" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."ADDRESSBOOK" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."ADDRESSBOOK" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."ADDRESSBOOK" MODIFY ("ADDRESSBOOK_IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "BITWORK"."BOARD" ADD CONSTRAINT "BOARD_PK" PRIMARY KEY ("BOARD_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BITWORK"."BOARD" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."BOARD" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."BOARD" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."BOARD" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."BOARD" MODIFY ("BOARD_IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "BITWORK"."COMMENTS" ADD CONSTRAINT "COMMENTS_PK" PRIMARY KEY ("CMT_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BITWORK"."COMMENTS" MODIFY ("BOARD_IDX" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."COMMENTS" MODIFY ("CMT_DATE" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."COMMENTS" MODIFY ("CMT_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."COMMENTS" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."COMMENTS" MODIFY ("CMT_IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMUTE
--------------------------------------------------------

  ALTER TABLE "BITWORK"."COMMUTE" ADD CONSTRAINT "COMMUTE_PK" PRIMARY KEY ("MEMBER_ID", "C_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BITWORK"."COMMUTE" MODIFY ("ON_TIME" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."COMMUTE" MODIFY ("C_DATE" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."COMMUTE" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMPANY
--------------------------------------------------------

  ALTER TABLE "BITWORK"."COMPANY" MODIFY ("COMPANY_EMP_CNT" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."COMPANY" ADD CONSTRAINT "UC_COMPANY_EMAIL" UNIQUE ("COMPANY_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BITWORK"."COMPANY" ADD CONSTRAINT "COMPANY_PK" PRIMARY KEY ("COMPANY_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BITWORK"."COMPANY" MODIFY ("COMPANY_PHONE" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."COMPANY" MODIFY ("COMPANY_NAME" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."COMPANY" MODIFY ("COMPANY_IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "BITWORK"."MEMBER" ADD CONSTRAINT "UC_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BITWORK"."MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BITWORK"."MEMBER" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."MEMBER" MODIFY ("POSITION" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."MEMBER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."MEMBER" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIGN
--------------------------------------------------------

  ALTER TABLE "BITWORK"."SIGN" MODIFY ("WRITER_NAME" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."SIGN" ADD CONSTRAINT "SIGN_PK" PRIMARY KEY ("DOC_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BITWORK"."SIGN" MODIFY ("DOC_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."SIGN" MODIFY ("DOC_STATUS" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."SIGN" MODIFY ("INSERT_DATE" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."SIGN" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."SIGN" MODIFY ("DOC_TITLE" NOT NULL ENABLE);
  ALTER TABLE "BITWORK"."SIGN" MODIFY ("DOC_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ADDRESSBOOK
--------------------------------------------------------

  ALTER TABLE "BITWORK"."ADDRESSBOOK" ADD CONSTRAINT "ADDRESSBOOK_COMPANY_FK" FOREIGN KEY ("COMPANY_IDX")
	  REFERENCES "BITWORK"."COMPANY" ("COMPANY_IDX") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "BITWORK"."BOARD" ADD CONSTRAINT "FK_BOARD_MEMBER_ID_MEMBER_ID" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "BITWORK"."MEMBER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "BITWORK"."COMMENTS" ADD FOREIGN KEY ("BOARD_IDX")
	  REFERENCES "BITWORK"."BOARD" ("BOARD_IDX") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMUTE
--------------------------------------------------------

  ALTER TABLE "BITWORK"."COMMUTE" ADD CONSTRAINT "FK_COMMUTE_MEMBER_ID_MEMBER_ID" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "BITWORK"."MEMBER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "BITWORK"."MEMBER" ADD CONSTRAINT "FK_MEMBER_COMPANY_IDX_COMPANY_" FOREIGN KEY ("COMPANY_IDX")
	  REFERENCES "BITWORK"."COMPANY" ("COMPANY_IDX") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SIGN
--------------------------------------------------------

  ALTER TABLE "BITWORK"."SIGN" ADD CONSTRAINT "FK_SIGN_MEMBER_ID_MEMBER_ID" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "BITWORK"."MEMBER" ("ID") ENABLE;
